jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # Adjust the path to the subdirectory where lock files are located
      - name: Verify lock file
        run: |
          if [ ! -f site/package-lock.json ] && [ ! -f site/npm-shrinkwrap.json ] && [ ! -f site/yarn.lock ]; then
            echo "No lock file found in 'site' directory. Please ensure you have a lock file (package-lock.json, npm-shrinkwrap.json, or yarn.lock) committed to the 'site' directory."
            exit 1
          fi

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Adjust path to install dependencies in the 'site' directory
      - name: Install dependencies
        run: npm ci --prefix site
        
      # Adjust path to build the project in the 'site' directory
      - name: Build
        run: npm run build --prefix site

      # Adjust path to verify the build output in the 'site' directory
      - name: Verify build output
        run: |
          if [ ! -d site/dist ]; then
            echo "Build directory 'site/dist' does not exist. Please check your build script."
            exit 1
          fi

      # Adjust path to set up GitHub Pages in the 'site' directory
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Adjust path to upload the build output from 'site/dist'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

